name: project2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  permission_handler: ^10.4.5
  dotted_border: ^2.1.0
  image_picker: ^1.0.4
  camera: ^0.11.0+2
  #tflite: ^1.1.2 todo try this for gpu
  tflite_v2: ^1.0.0
  dropdown_search: ^5.0.6
  otp_text_field: ^1.1.3
  timer_count_down: ^2.2.2
  image: ^4.2.0
  path_provider: ^2.0.11
  processing_camera_image: ^0.0.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  win32: ^5.5.4


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/paper_model2.tflite
    - assets/paper_model2.txt

  fonts:
    - family: arabic
      fonts:
        - asset: assets/fonts/Cairo.ttf
    - family: english
      fonts:
        - asset: assets/fonts/Barlow.ttf

